### ISSUE TITLE
如何排除一些页面的ai摘要

### ISSUE THREAD

**Issue by Bytelv** [zhheo/Post-Abstract-AI#1]
hexo 主题：stellar
tianliGPT_postSelector ='.md-text.content'

在加入ai摘要时，一些页面如（动态，友链）也会加入ai摘要，应如何排除这些页面的ai摘要？

**Comment by zhheo** [comment]
改为‘.md-text.content.post’即可

**Comment by Bytelv** [comment]
> 改为‘.md-text.content.post’即可

感谢

**Comment by so1ve** [comment]
或者你手动加一个配置，然后在模板里头判断该页面应不应当添加摘要

**Comment by bianyukun1213** [comment]
我觉得最好能提供一个变量，根据变量决定是否生成摘要，这样比较灵活。比如，使用 `hexo-blog-encrypt` 加密的文章，在解密前不生成摘要，在解密后再生成摘要。

**Comment by zhheo** [comment]
> 我觉得最好能提供一个变量，根据变量决定是否生成摘要，这样比较灵活。比如，使用 `hexo-blog-encrypt` 加密的文章，在解密前不生成摘要，在解密后再生成摘要。

建议用js来控制js文件的引入，或者编辑js文件修改逻辑也可以。
我会在近期添加黑名单功能，也可以等待一下
