### ISSUE TITLE
如何在 valaxy-theme-yun 中使用

### ISSUE THREAD

**Issue by Big-Cake-jpg** [zhheo/Post-Abstract-AI#11]
自己摸索了半天也没找出个办法来，没办法就来开个 Issue（

**Comment by zhheo** [comment]
tianliGPT_postSelector为.content .markdown-body
tianliGPT_postURL为*/posts/*

**Comment by Big-Cake-jpg** [comment]
> tianliGPT_postSelector为.content .markdown-body tianliGPT_postURL为*/posts/*

抱歉。你可能没理解我的意思。

我是指，应该如何编写 Vue 组件或者插入 JS 与 CSS？我尝试在根目录下的 `index.html` 的 `body` 部分插入并配置好选择器与 `postURL`，似乎不起作用。

**Comment by zhheo** [comment]
这部分我也不太清楚，因为不同主题的编写方式不同。
可以尝试编写footer部分代码，将tianliGPT中的内容插入到footer中
