### ISSUE TITLE
wordpress-OneNav主题

### ISSUE THREAD

**Issue by QinCoCo** [zhheo/Post-Abstract-AI#14]
wordpress-OneNav主题

**Comment by zhheo** [comment]
可以提供一个使用这个主题的地址吗

**Comment by tyhguan** [comment]
> 可以提供一个使用这个主题的地址吗

这个是一个导航主题，下面是一个文章页面
文章页：https://www.ruii6.com/1242.html

**Comment by zhheo** [comment]
tianliGPT_postSelector为 .post-template-default .panel-body
