### ISSUE TITLE
请求支持wordpress-argon，thx

### ISSUE THREAD

**Issue by Destiny-Lu** [zhheo/Post-Abstract-AI#17]
https://github.com/solstice23/argon-theme

**Comment by zhheo** [comment]
tianliGPT_postSelector：  #post-content
tianliGPT_postURL：*/archives/*

**Comment by Destiny-Lu** [comment]
![image](https://github.com/zhheo/Post-Abstract-AI/assets/80380290/83c4bed0-6783-4948-ad70-b9d100a5daf7)
你好，我在页头和页尾都分别尝试加入如下代码，前端页面并没有显式摘要配置正确。求助

**Comment by zhheo** [comment]
请提供地址

**Comment by Destiny-Lu** [comment]
@zhheo http://s2.i7xl.cn:31083/

**Comment by zhheo** [comment]
我观察到你的选择器为：#post-content
而实际应该填写的为：#post_content

**Comment by Destiny-Lu** [comment]
![image](https://github.com/zhheo/Post-Abstract-AI/assets/80380290/cffcce90-e0aa-47a8-af03-1f390178b19a)
@zhheo 感谢您的答复，但是我改成#post_content以后依然会输出这行日志，我现在已经修改为#post_content，您可以再检查一下

**Comment by zhheo** [comment]
看来主题适配的道路非常的艰辛，因为每个人的配置不同造成了这个问题。
删除Let tianLiGPT_postURL： "/archives/;整行即可

**Comment by zhheo** [comment]
是你自己添加的代码部分，删除tianLiGPT_postURL变量

**Comment by Destiny-Lu** [comment]
@zhheo 去掉后确实某些时候可以显示了，但是因为某些原因，第一次点进文章并不能正常显示摘要。必须在文章页刷新界面才能显示。同时，因为我的博客上部署了一个我自己的大模型机器人，如果刷新网页就会让对话历史消失，因此我可能无法设定进入新网页直接刷新整个页面这个操作。这有办法解决吗，感谢！

**Comment by zhheo** [comment]
这是pjax的原因造成的。按照前面的主题说明：
```
<script>
window.pjaxLoaded = function() {

1/页面每次跳转都会执行这里的代码

checkURLAndRun();`}
</script>
```

因为OCR识别原因可能代码有问题，请自行调整
使用这种写法，运行`checkURLAndRun();`

这个代码填写在所有填写的代码之后

**Comment by Destiny-Lu** [comment]
完美解决所有问题！ 感谢您的耐心指导。

**Comment by MicIsHere** [comment]
请问您是如何解决的？
我按照给出的方案填写后，第一次点进文章依旧不能正常显示摘要
![IMG_3363](https://github.com/zhheo/Post-Abstract-AI/assets/76840547/1af2f2c4-5bfe-4050-a653-372b1afb7805)
