### ISSUE TITLE
洪哥，请问如何解决每次页面不刷新，但是脚本重复执行出现的多个AI摘要问题呢？

### ISSUE THREAD

**Issue by a-lhliang** [zhheo/Post-Abstract-AI#2]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/39986022/232314550-76786bd0-6355-4034-9e8f-bb8afab0ca5e.png">

**Comment by zhheo** [comment]
观察到似乎是开启了pjax，请尝试在js的script代码中加入data-pjax，例如<script data-pjax src="https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.5/tianli_gpt.js"></script>
我会持续跟踪这个问题。

**Comment by a-lhliang** [comment]
更新0.6后已经解决，但是我看大家都是插入到<article class="post-content" id="article-container">之前，我这个奇怪总是在后面

**Comment by zhheo** [comment]
没太理解之前和之后，我目前看到显示是正常的。如果有更多的问题，麻烦请更详细的说明，建议配图
