### ISSUE TITLE
hexo-icarus主题求助

### ISSUE THREAD

**Issue by DomeenoH** [zhheo/Post-Abstract-AI#24]
[主题仓库](https://github.com/ppoffice/hexo-theme-icarus)
[博客](https://blog.dominoh.com/)
请问tianliGPT_postSelector应该如何填写？

**Comment by qxchuckle** [comment]
.article>.content

**Comment by DomeenoH** [comment]
感谢

**Comment by cyhasuka** [comment]
@DomeenoH @qxchuckle 您好，请问您的部署成功了吗，下面的代码需要插入在哪个文件中呀，谢谢您！！！
```
<link rel="stylesheet" href="https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.css"></link>
            <script let tianliGPT_postSelector = '.article>.content'></script>
            <script let tianliGPT_key = '************'></script>
            <script src={url_for('https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.min.js')} defer></script>
```

**Comment by qxchuckle** [comment]
> @DomeenoH @qxchuckle您好，请问您的部署成功了吗，下面的代码需要插入在哪个文件中呀，谢谢您！！！
> 
> ```
> <link rel="stylesheet" href="https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.css"></link>
>             <script let tianliGPT_postSelector = '.article>.content'></script>
>             <script let tianliGPT_key = '************'></script>
>             <script src={url_for('https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.min.js')} defer></script>
> ```

这是几个html标签，需要添加到html文件中，或者可以生成html的模板或脚本文件中，通常link标签添加到head末尾，而script标签添加到body末尾

**Comment by cyhasuka** [comment]
> > @DomeenoH @qxchuckle您好，请问您的部署成功了吗，下面的代码需要插入在哪个文件中呀，谢谢您！！！
> > ```
> > <link rel="stylesheet" href="https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.css"></link>
> >             <script let tianliGPT_postSelector = '.article>.content'></script>
> >             <script let tianliGPT_key = '************'></script>
> >             <script src={url_for('https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.min.js')} defer></script>
> > ```
> 
> 这是几个html标签，需要添加到html文件中，或者可以生成html的模板或脚本文件中，通常link标签添加到head末尾，而script标签添加到body末尾

@qxchuckle 谢谢您的回复，我将link标签添加到head末尾，script标签添加到body末尾，但仍然无法显示 AI 界面。[我的网站](https://cuiyuhao.com/20190420/Rplidar-A3%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B%EF%BC%88%E5%9C%A8A2%E5%9F%BA%E7%A1%80%E4%B8%8A%EF%BC%89/)
请问是不是下面的参数设置有问题，我把这些放在了`scripts.jsx`中的`return <Fragment>`中，不知是否正确。我是前端小白，见谅o(╥﹏╥)o
```
return <Fragment>
            {/* <script let tianliGPT_postSelector = '.article>.content'></script> */}
            {/* <script let tianliGPT_key = '********************'></script> */}
            <script src={url_for('https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.min.js')} defer></script>
            <script tianliGPT_postSelector={ '.article>.content' }></script>
            <script tianliGPT_key={ '**********************' }></script>
            <script src={url_for('/js/main.js')} defer></script>
        </Fragment>;
```
