### ISSUE TITLE
【严重bug】 url过长会导致TianliGPT无法正常获得文章摘要

### ISSUE THREAD

**Issue by Nihility-Ming** [zhheo/Post-Abstract-AI#35]
【严重bug】
我的blog的文章url是中文的，所以部分文章urlencoding后url过长，例如：

https://www.traderpuma.com/%E8%A1%8C%E6%83%85%E5%88%86%E6%9E%90/2023/2023-10-24%20%E6%AF%94%E7%89%B9%E5%B8%81%E8%A1%8C%E6%83%85%E5%88%86%E6%9E%90%EF%BC%9A%E5%91%A8%E7%BA%BF%E5%A4%A7%E7%AA%81%E7%A0%B4%EF%BC%8C%E5%A4%A7%E7%89%9B%E5%B8%82%E5%9B%9E%E6%9D%A5%E4%BA%86%EF%BC%81.html

https://www.traderpuma.com/%E4%BA%A4%E6%98%93%E5%BF%83%E5%BE%97/%E8%82%A5%E5%AE%85%E6%AF%94%E7%89%B9%E5%B8%81%E3%80%81%E6%B3%95%E5%B8%88Tony%E5%B8%81%E5%9C%88%E4%BA%A4%E6%98%93%E9%AB%98%E6%89%8B%E7%9A%84%E4%BA%A4%E6%98%93%E7%AD%96%E7%95%A5%E6%80%BB%E7%BB%93.html

https://www.traderpuma.com/%E4%BA%A4%E6%98%93%E5%BF%83%E5%BE%97/%E8%B6%8B%E5%8A%BF%E4%BA%A4%E6%98%93%E8%80%85%E7%9A%84%E6%9C%80%E5%A4%A7%E9%9A%BE%E9%A2%98%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E8%BF%99%E4%BA%9B%E9%9A%BE%E9%A2%98%EF%BC%9F.html

会导致TianliGPT无法正常获得文章摘要，提示403错误！

**Comment by zhheo** [comment]
问题已经提交给tianli了，建议留下您的uid

**Comment by Nihility-Ming** [comment]
> 问题已经提交给tianli了，建议留下您的uid

用户ID：582

**Comment by TIANLI0** [comment]
> > 问题已经提交给tianli了，建议留下您的uid
> 
> 用户ID：582

您好，等今天上完课才能为你排查，请谅解

**Comment by Nihility-Ming** [comment]
> > > 问题已经提交给tianli了，建议留下您的uid
> > 
> > 
> > 用户ID：582
> 
> 您好，等今天上完课才能为你排查，请谅解

好的，还有我的积分无故消失了许多，也帮忙解决下，谢谢！

**Comment by TIANLI0** [comment]
> 582

您好，问题已解决，相关补偿已发放至您的账号，请登录确认，如有问题请联系 wutianli@tianli0.top

**Comment by Nihility-Ming** [comment]
> > 582
> 
> 您好，问题已解决，相关补偿已发放至您的账号，请登录确认，如有问题请联系 [wutianli@tianli0.top](mailto:wutianli@tianli0.top)

新问题已经发到您邮箱~

**Comment by cyhasuka** [comment]
@zhheo @TIANLI0 似乎该问题仍然存在，例如：
[这篇文章无法获取摘要内容](https://cuiyuhao.com/20230109/WiFi%206%E7%BB%88%E7%AB%A0%EF%BC%9FROG%E6%97%97%E8%88%B0%E4%B8%87%E5%85%86%E8%B7%AF%E7%94%B1GT-AX11000Pro%E5%BC%80%E7%AE%B1%E8%AF%84%E6%B5%8B/)
[这篇文章可以正常获取](https://cuiyuhao.com/20231227/Autoware%20%E8%BD%AF%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/)
我的ID：728

**Comment by TIANLI0** [comment]
> @zhheo @TIANLI0 似乎该问题仍然存在，例如：
> [这篇文章无法获取摘要内容](https://cuiyuhao.com/20230109/WiFi%206%E7%BB%88%E7%AB%A0%EF%BC%9FROG%E6%97%97%E8%88%B0%E4%B8%87%E5%85%86%E8%B7%AF%E7%94%B1GT-AX11000Pro%E5%BC%80%E7%AE%B1%E8%AF%84%E6%B5%8B/)
> [这篇文章可以正常获取](https://cuiyuhao.com/20231227/Autoware%20%E8%BD%AF%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/)
> 我的ID：728

抱歉给您带来不好的体验，最近忙于考试，可能十号左右才能去定位问题，为表歉意，届时我将提供足够的补偿，敬请谅解

**Comment by cyhasuka** [comment]
> > @zhheo @TIANLI0 似乎该问题仍然存在，例如：
> > [这篇文章无法获取摘要内容](https://cuiyuhao.com/20230109/WiFi%206%E7%BB%88%E7%AB%A0%EF%BC%9FROG%E6%97%97%E8%88%B0%E4%B8%87%E5%85%86%E8%B7%AF%E7%94%B1GT-AX11000Pro%E5%BC%80%E7%AE%B1%E8%AF%84%E6%B5%8B/)
> > [这篇文章可以正常获取](https://cuiyuhao.com/20231227/Autoware%20%E8%BD%AF%E4%BB%B6%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/)
> > 我的ID：728
> 
> 抱歉给您带来不好的体验，最近忙于考试，可能十号左右才能去定位问题，为表歉意，届时我将提供足够的补偿，敬请谅解

好的，谢谢，期待后续更新 ~
另预祝考试顺利！

**Comment by cyhasuka** [comment]
@TIANLI0 @zhheo 更新：
我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？）
提供新的测试链接，上文链接已失效：
[正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/)
[异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)

**Comment by zhheo** [comment]
> @TIANLI0 @zhheo 更新： 我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？） 提供新的测试链接，上文链接已失效： [正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/) [异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)

和标题长度无关。不过目前的错误机制比较差，等tianli考完试之后，将整个错误反馈的具体情况都返回到前端，这样更加方便调试。

**Comment by cyhasuka** [comment]
> > @TIANLI0 @zhheo 更新： 我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？） 提供新的测试链接，上文链接已失效： [正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/) [异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)
> 
> 和标题长度无关。不过目前的错误机制比较差，等tianli考完试之后，将整个错误反馈的具体情况都返回到前端，这样更加方便调试。

了解了，谢谢，期待后续更新

**Comment by TIANLI0** [comment]
不好意思，鸽了，这几天在医院，有空第一时间处理

**Comment by TIANLI0** [comment]
> 不好意思，鸽了，这几天在医院，有空第一时间处理



> > > @TIANLI0 @zhheo 更新： 我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？） 提供新的测试链接，上文链接已失效： [正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/) [异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)
> > 
> > 
> > 和标题长度无关。不过目前的错误机制比较差，等tianli考完试之后，将整个错误反馈的具体情况都返回到前端，这样更加方便调试。
> 
> 了解了，谢谢，期待后续更新

请问问题现在问题还存在吗，之前回复错楼层了
![image](https://github.com/zhheo/Post-Abstract-AI/assets/52097638/fce47516-c6e5-4ac5-b400-59abe690988c)

**Comment by cyhasuka** [comment]
> > 不好意思，鸽了，这几天在医院，有空第一时间处理
> 
> > > > @TIANLI0 @zhheo 更新： 我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？） 提供新的测试链接，上文链接已失效： [正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/) [异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)
> > > 
> > > 
> > > 和标题长度无关。不过目前的错误机制比较差，等tianli考完试之后，将整个错误反馈的具体情况都返回到前端，这样更加方便调试。
> > 
> > 
> > 了解了，谢谢，期待后续更新
> 
> 请问问题现在问题还存在吗，之前回复错楼层了 ![image](https://private-user-images.githubusercontent.com/52097638/296827613-fce47516-c6e5-4ac5-b400-59abe690988c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzQ1MjUsIm5iZiI6MTcwNTM3NDIyNSwicGF0aCI6Ii81MjA5NzYzOC8yOTY4Mjc2MTMtZmNlNDc1MTYtYzZlNS00YWM1LWI0MDAtNTlhYmU2OTA5ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MGNkMTY5YTM1ODgxY2RhYTQ3ZTc2YjU5YzdiMzI0MjM3YjljY2ViYjJlZTJjNzk1YWRhYWM4ZmE0YTUxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xX3KjipE4UwOn85tmSPZRiIvCbCPNywhqnxSoy50TMQ)

问题还存在，我暂时切换到另一个API来调用TianliGPT，似乎是此API与icirus主题的兼容性问题

**Comment by TIANLI0** [comment]
> > > 不好意思，鸽了，这几天在医院，有空第一时间处理
> > 
> > 
> > > > > @TIANLI0 @zhheo 更新： 我尝试将我的文章中文链接转换成16进制短连接表示，但似乎无效，提交仍然报403 Error，TianliGPT是否可获得文章摘要似乎与文章标题长度相关（猜测？） 提供新的测试链接，上文链接已失效： [正常链接，标题21字符](https://cuiyuhao.com/posts/15d39967/) [异常链接，标题48字符](https://cuiyuhao.com/posts/727a344e/)
> > > > 
> > > > 
> > > > 和标题长度无关。不过目前的错误机制比较差，等tianli考完试之后，将整个错误反馈的具体情况都返回到前端，这样更加方便调试。
> > > 
> > > 
> > > 了解了，谢谢，期待后续更新
> > 
> > 
> > 请问问题现在问题还存在吗，之前回复错楼层了 ![image](https://private-user-images.githubusercontent.com/52097638/296827613-fce47516-c6e5-4ac5-b400-59abe690988c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzQ1MjUsIm5iZiI6MTcwNTM3NDIyNSwicGF0aCI6Ii81MjA5NzYzOC8yOTY4Mjc2MTMtZmNlNDc1MTYtYzZlNS00YWM1LWI0MDAtNTlhYmU2OTA5ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAzMDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MGNkMTY5YTM1ODgxY2RhYTQ3ZTc2YjU5YzdiMzI0MjM3YjljY2ViYjJlZTJjNzk1YWRhYWM4ZmE0YTUxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xX3KjipE4UwOn85tmSPZRiIvCbCPNywhqnxSoy50TMQ)
> 
> 问题还存在，我暂时切换到另一个API来调用TianliGPT，似乎是此API与icirus主题的兼容性问题

我查了一下，是因为Heo的前端是Get请求，当内容过长时发送到后端的内容可能会出现编码错误，你现在使用的是POST请求的，因此没有相关问题，为表歉意将会给您发送补偿，请注意查收

**Comment by cyhasuka** [comment]
了解了，谢谢您提供的帮助！

Tianli ***@***.***>于2024年1月16日 周二18:05写道：
