### ISSUE TITLE
hexo-icarus主题代码插入求教

### ISSUE THREAD

**Issue by cyhasuka** [zhheo/Post-Abstract-AI#36]
RT.，在另外的issue #24 中有提到`tianliGPT_postSelector = '.article>.content'`。我将下面的代码插入到`script.jsx`中的`return`中无效。请问作者，这个主题中，下面的部分要插入到什么位置呀？另外如果插入成功但没有填写key，是否会显示AI界面（用于debug）？ 谢谢您的帮助！

```
<link rel="stylesheet" href="https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.css"></link>
<script let tianliGPT_postSelector = '.article>.content'></script>
<script let tianliGPT_key = '************'></script>
<script src={url_for('https://cdn1.tianli0.top/gh/zhheo/Post-Abstract-AI@0.15.2/tianli_gpt.min.js')} defer></script>
```

**Comment by zhheo** [comment]
debug的key就是readme的5Q5mpqRK5DkwT1X9Gi5e
这段代码是html代码，你可以插入到例如head标签内。比如添加统计代码的位置。

**Comment by cyhasuka** [comment]
谢谢，该问题已解决，将关闭issue。另期待中文url问题后续更新~
