### ISSUE TITLE
Heo主题问题

### ISSUE THREAD

**Issue by LjyLab** [zhheo/Post-Abstract-AI#37]
请原谅我问一个与该项目毫无关系的问题，我想问一下关于您博客主题关于页面的进度条是如何制作的
![image](https://github.com/zhheo/Post-Abstract-AI/assets/36144129/0c4f40b7-f39e-42af-9fc5-5eefc519e63e)

**Comment by zhheo** [comment]
sketch绘制的，你可以理解为类似画图软件画的

**Comment by LjyLab** [comment]
能分享一下sketch文件嘛 :)

**Comment by zhheo** [comment]
已发送至邮箱：admin@cuonc.com;
