### ISSUE TITLE
【已解决】hexo-theme-redefine主题

### ISSUE THREAD

**Issue by Elecmark** [zhheo/Post-Abstract-AI#42]
适配一下hexo-theme-redefine主题，谢谢！
示例地址是：https://ohevan.com/hexo-theme-redefine-intro.html

**Comment by Elecmark** [comment]
试出来了😄
tianliGPT_postSelector = '.article-content.markdown-body';

**Comment by zhheo** [comment]
感谢你公开代码，即将加入到文档中
