### ISSUE TITLE
Argon主题在添加脚本后，第一次打开文章无法加载摘要

### ISSUE THREAD

**Issue by MicIsHere** [zhheo/Post-Abstract-AI#45]
按照[教程](https://docs_s.tianli0.top/theme/wordpress-argon.html)，将代码添加到页脚后，第一次打开文章不加载摘要。
在搜索项目的Issus后尝试按照[#17](https://github.com/zhheo/Post-Abstract-AI/issues/17#issuecomment-1628663411)修改，但问题依旧。
我的网站链接是:  https://cutemic.cn/

以下截图为按照[#17](https://github.com/zhheo/Post-Abstract-AI/issues/17#issuecomment-1628663411)对教程中的原代码进行修改
![IMG_3363](https://github.com/zhheo/Post-Abstract-AI/assets/76840547/ca3c7e1f-bcce-4ef4-b838-50a7d626b0d5)

**Comment by zhheo** [comment]
我观察到你那个图片上顶部红字的说明已经很清楚了。页面首次加载的时候需要执行一次window.pjaxLoaded（）；

这行代码插入任意script标签内即可
