### ISSUE TITLE
hexo-theme-redefine 第一次进入页面的时候没有显示摘要，控制台报错TypeError: document.addEventListener(...) is not a function

### ISSUE THREAD

**Issue by SunXin121** [zhheo/Post-Abstract-AI#47]
hexo-theme-redefine 第一次进入页面的时候没有显示摘要，控制台报错
TypeError: document.addEventListener(...) is not a function
再次刷新页面后才显示摘要

**Comment by zhheo** [comment]
麻烦提供复现问题的地址

**Comment by zhheo** [comment]
长时间未回复，关闭此议题，如需恢复请重新开启
